version: '3.8'

services:
  springboot-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/card-order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: card-order
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - springboot-mysql-network


volumes:
  mysql_data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
